baseURL = 'https://nativeboundunbound.org/'
languageCode = 'en-us'
title = 'Native Boundâ€”Unbound'
theme = 'hugOpenProps'
copyright = 'All rights reserved Native Bound Unbound'

[params]
  author = ''
  typekit = 'https://use.typekit.net/nci1ctu.css'

# [menu]
#   [[menu.main]]
#     name = 'Home'
#     url = '/'
#     weight = -1
#   [[menu.main]]
#     name = 'About'
#     url = '/about/'
#     weight = 10